-----------------------------------------------------------------------
--  Jason.Tickets.Models -- Jason.Tickets.Models
-----------------------------------------------------------------------
--  File generated by ada-gen DO NOT MODIFY
--  Template used: templates/model/package-body.xhtml
--  Ada Generator: https://ada-gen.googlecode.com/svn/trunk Revision 1095
-----------------------------------------------------------------------
--  Copyright (C) 2020 Stephane.Carrez
--  Written by Stephane.Carrez (Stephane.Carrez@gmail.com)
--
--  Licensed under the Apache License, Version 2.0 (the "License");
--  you may not use this file except in compliance with the License.
--  You may obtain a copy of the License at
--
--      http://www.apache.org/licenses/LICENSE-2.0
--
--  Unless required by applicable law or agreed to in writing, software
--  distributed under the License is distributed on an "AS IS" BASIS,
--  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
--  See the License for the specific language governing permissions and
--  limitations under the License.
-----------------------------------------------------------------------
with Ada.Unchecked_Deallocation;
with Util.Beans.Objects.Time;
with ASF.Events.Faces.Actions;
package body Jason.Tickets.Models is

   use type ADO.Objects.Object_Record_Access;
   use type ADO.Objects.Object_Ref;

   pragma Warnings (Off, "formal parameter * is not referenced");

   function Ticket_Key (Id : in ADO.Identifier) return ADO.Objects.Object_Key is
      Result : ADO.Objects.Object_Key (Of_Type  => ADO.Objects.KEY_INTEGER,
                                       Of_Class => TICKET_DEF'Access);
   begin
      ADO.Objects.Set_Value (Result, Id);
      return Result;
   end Ticket_Key;

   function Ticket_Key (Id : in String) return ADO.Objects.Object_Key is
      Result : ADO.Objects.Object_Key (Of_Type  => ADO.Objects.KEY_INTEGER,
                                       Of_Class => TICKET_DEF'Access);
   begin
      ADO.Objects.Set_Value (Result, Id);
      return Result;
   end Ticket_Key;

   function "=" (Left, Right : Ticket_Ref'Class) return Boolean is
   begin
      return ADO.Objects.Object_Ref'Class (Left) = ADO.Objects.Object_Ref'Class (Right);
   end "=";

   procedure Set_Field (Object : in out Ticket_Ref'Class;
                        Impl   : out Ticket_Access) is
      Result : ADO.Objects.Object_Record_Access;
   begin
      Object.Prepare_Modify (Result);
      Impl := Ticket_Impl (Result.all)'Access;
   end Set_Field;

   --  Internal method to allocate the Object_Record instance
   procedure Allocate (Object : in out Ticket_Ref) is
      Impl : Ticket_Access;
   begin
      Impl := new Ticket_Impl;
      Impl.Version := 0;
      Impl.Ident := 0;
      Impl.Create_Date := ADO.DEFAULT_TIME;
      Impl.Priority := 0;
      Impl.Status := Jason.Tickets.Models.Status_Type'First;
      Impl.Update_Date := ADO.DEFAULT_TIME;
      Impl.Ticket_Type := Jason.Tickets.Models.Ticket_Type'First;
      Impl.Duration := 0;
      Impl.Progress := 0;
      ADO.Objects.Set_Object (Object, Impl.all'Access);
   end Allocate;

   -- ----------------------------------------
   --  Data object: Ticket
   -- ----------------------------------------

   procedure Set_Id (Object : in out Ticket_Ref;
                     Value  : in ADO.Identifier) is
      Impl : Ticket_Access;
   begin
      Set_Field (Object, Impl);
      ADO.Objects.Set_Field_Key_Value (Impl.all, 1, Value);
   end Set_Id;

   function Get_Id (Object : in Ticket_Ref)
                  return ADO.Identifier is
      Impl : constant Ticket_Access
         := Ticket_Impl (Object.Get_Object.all)'Access;
   begin
      return Impl.Get_Key_Value;
   end Get_Id;


   function Get_Version (Object : in Ticket_Ref)
                  return Integer is
      Impl : constant Ticket_Access
         := Ticket_Impl (Object.Get_Load_Object.all)'Access;
   begin
      return Impl.Version;
   end Get_Version;


   procedure Set_Summary (Object : in out Ticket_Ref;
                           Value : in String) is
      Impl : Ticket_Access;
   begin
      Set_Field (Object, Impl);
      ADO.Objects.Set_Field_String (Impl.all, 3, Impl.Summary, Value);
   end Set_Summary;

   procedure Set_Summary (Object : in out Ticket_Ref;
                          Value  : in Ada.Strings.Unbounded.Unbounded_String) is
      Impl : Ticket_Access;
   begin
      Set_Field (Object, Impl);
      ADO.Objects.Set_Field_Unbounded_String (Impl.all, 3, Impl.Summary, Value);
   end Set_Summary;

   function Get_Summary (Object : in Ticket_Ref)
                 return String is
   begin
      return Ada.Strings.Unbounded.To_String (Object.Get_Summary);
   end Get_Summary;
   function Get_Summary (Object : in Ticket_Ref)
                  return Ada.Strings.Unbounded.Unbounded_String is
      Impl : constant Ticket_Access
         := Ticket_Impl (Object.Get_Load_Object.all)'Access;
   begin
      return Impl.Summary;
   end Get_Summary;


   procedure Set_Ident (Object : in out Ticket_Ref;
                        Value  : in Integer) is
      Impl : Ticket_Access;
   begin
      Set_Field (Object, Impl);
      ADO.Objects.Set_Field_Integer (Impl.all, 4, Impl.Ident, Value);
   end Set_Ident;

   function Get_Ident (Object : in Ticket_Ref)
                  return Integer is
      Impl : constant Ticket_Access
         := Ticket_Impl (Object.Get_Load_Object.all)'Access;
   begin
      return Impl.Ident;
   end Get_Ident;


   procedure Set_Create_Date (Object : in out Ticket_Ref;
                              Value  : in Ada.Calendar.Time) is
      Impl : Ticket_Access;
   begin
      Set_Field (Object, Impl);
      ADO.Objects.Set_Field_Time (Impl.all, 5, Impl.Create_Date, Value);
   end Set_Create_Date;

   function Get_Create_Date (Object : in Ticket_Ref)
                  return Ada.Calendar.Time is
      Impl : constant Ticket_Access
         := Ticket_Impl (Object.Get_Load_Object.all)'Access;
   begin
      return Impl.Create_Date;
   end Get_Create_Date;


   procedure Set_Priority (Object : in out Ticket_Ref;
                           Value  : in Integer) is
      Impl : Ticket_Access;
   begin
      Set_Field (Object, Impl);
      ADO.Objects.Set_Field_Integer (Impl.all, 6, Impl.Priority, Value);
   end Set_Priority;

   function Get_Priority (Object : in Ticket_Ref)
                  return Integer is
      Impl : constant Ticket_Access
         := Ticket_Impl (Object.Get_Load_Object.all)'Access;
   begin
      return Impl.Priority;
   end Get_Priority;


   procedure Set_Status (Object : in out Ticket_Ref;
                         Value  : in Jason.Tickets.Models.Status_Type) is
      procedure Set_Field_Enum is
         new ADO.Objects.Set_Field_Operation (Status_Type);
      Impl : Ticket_Access;
   begin
      Set_Field (Object, Impl);
      Set_Field_Enum (Impl.all, 7, Impl.Status, Value);
   end Set_Status;

   function Get_Status (Object : in Ticket_Ref)
                  return Jason.Tickets.Models.Status_Type is
      Impl : constant Ticket_Access
         := Ticket_Impl (Object.Get_Load_Object.all)'Access;
   begin
      return Impl.Status;
   end Get_Status;


   procedure Set_Description (Object : in out Ticket_Ref;
                               Value : in String) is
      Impl : Ticket_Access;
   begin
      Set_Field (Object, Impl);
      ADO.Objects.Set_Field_String (Impl.all, 8, Impl.Description, Value);
   end Set_Description;

   procedure Set_Description (Object : in out Ticket_Ref;
                              Value  : in Ada.Strings.Unbounded.Unbounded_String) is
      Impl : Ticket_Access;
   begin
      Set_Field (Object, Impl);
      ADO.Objects.Set_Field_Unbounded_String (Impl.all, 8, Impl.Description, Value);
   end Set_Description;

   function Get_Description (Object : in Ticket_Ref)
                 return String is
   begin
      return Ada.Strings.Unbounded.To_String (Object.Get_Description);
   end Get_Description;
   function Get_Description (Object : in Ticket_Ref)
                  return Ada.Strings.Unbounded.Unbounded_String is
      Impl : constant Ticket_Access
         := Ticket_Impl (Object.Get_Load_Object.all)'Access;
   begin
      return Impl.Description;
   end Get_Description;


   procedure Set_Update_Date (Object : in out Ticket_Ref;
                              Value  : in Ada.Calendar.Time) is
      Impl : Ticket_Access;
   begin
      Set_Field (Object, Impl);
      ADO.Objects.Set_Field_Time (Impl.all, 9, Impl.Update_Date, Value);
   end Set_Update_Date;

   function Get_Update_Date (Object : in Ticket_Ref)
                  return Ada.Calendar.Time is
      Impl : constant Ticket_Access
         := Ticket_Impl (Object.Get_Load_Object.all)'Access;
   begin
      return Impl.Update_Date;
   end Get_Update_Date;


   procedure Set_Ticket_Type (Object : in out Ticket_Ref;
                              Value  : in Jason.Tickets.Models.Ticket_Type) is
      procedure Set_Field_Enum is
         new ADO.Objects.Set_Field_Operation (Ticket_Type);
      Impl : Ticket_Access;
   begin
      Set_Field (Object, Impl);
      Set_Field_Enum (Impl.all, 10, Impl.Ticket_Type, Value);
   end Set_Ticket_Type;

   function Get_Ticket_Type (Object : in Ticket_Ref)
                  return Jason.Tickets.Models.Ticket_Type is
      Impl : constant Ticket_Access
         := Ticket_Impl (Object.Get_Load_Object.all)'Access;
   begin
      return Impl.Ticket_Type;
   end Get_Ticket_Type;


   procedure Set_Duration (Object : in out Ticket_Ref;
                           Value  : in Integer) is
      Impl : Ticket_Access;
   begin
      Set_Field (Object, Impl);
      ADO.Objects.Set_Field_Integer (Impl.all, 11, Impl.Duration, Value);
   end Set_Duration;

   function Get_Duration (Object : in Ticket_Ref)
                  return Integer is
      Impl : constant Ticket_Access
         := Ticket_Impl (Object.Get_Load_Object.all)'Access;
   begin
      return Impl.Duration;
   end Get_Duration;


   procedure Set_Progress (Object : in out Ticket_Ref;
                           Value  : in Integer) is
      Impl : Ticket_Access;
   begin
      Set_Field (Object, Impl);
      ADO.Objects.Set_Field_Integer (Impl.all, 12, Impl.Progress, Value);
   end Set_Progress;

   function Get_Progress (Object : in Ticket_Ref)
                  return Integer is
      Impl : constant Ticket_Access
         := Ticket_Impl (Object.Get_Load_Object.all)'Access;
   begin
      return Impl.Progress;
   end Get_Progress;


   procedure Set_Project (Object : in out Ticket_Ref;
                          Value  : in Jason.Projects.Models.Project_Ref'Class) is
      Impl : Ticket_Access;
   begin
      Set_Field (Object, Impl);
      ADO.Objects.Set_Field_Object (Impl.all, 13, Impl.Project, Value);
   end Set_Project;

   function Get_Project (Object : in Ticket_Ref)
                  return Jason.Projects.Models.Project_Ref'Class is
      Impl : constant Ticket_Access
         := Ticket_Impl (Object.Get_Load_Object.all)'Access;
   begin
      return Impl.Project;
   end Get_Project;


   procedure Set_Creator (Object : in out Ticket_Ref;
                          Value  : in AWA.Users.Models.User_Ref'Class) is
      Impl : Ticket_Access;
   begin
      Set_Field (Object, Impl);
      ADO.Objects.Set_Field_Object (Impl.all, 14, Impl.Creator, Value);
   end Set_Creator;

   function Get_Creator (Object : in Ticket_Ref)
                  return AWA.Users.Models.User_Ref'Class is
      Impl : constant Ticket_Access
         := Ticket_Impl (Object.Get_Load_Object.all)'Access;
   begin
      return Impl.Creator;
   end Get_Creator;

   --  Copy of the object.
   procedure Copy (Object : in Ticket_Ref;
                   Into   : in out Ticket_Ref) is
      Result : Ticket_Ref;
   begin
      if not Object.Is_Null then
         declare
            Impl : constant Ticket_Access
              := Ticket_Impl (Object.Get_Load_Object.all)'Access;
            Copy : constant Ticket_Access
              := new Ticket_Impl;
         begin
            ADO.Objects.Set_Object (Result, Copy.all'Access);
            Copy.Copy (Impl.all);
            Copy.Version := Impl.Version;
            Copy.Summary := Impl.Summary;
            Copy.Ident := Impl.Ident;
            Copy.Create_Date := Impl.Create_Date;
            Copy.Priority := Impl.Priority;
            Copy.Status := Impl.Status;
            Copy.Description := Impl.Description;
            Copy.Update_Date := Impl.Update_Date;
            Copy.Ticket_Type := Impl.Ticket_Type;
            Copy.Duration := Impl.Duration;
            Copy.Progress := Impl.Progress;
            Copy.Project := Impl.Project;
            Copy.Creator := Impl.Creator;
         end;
      end if;
      Into := Result;
   end Copy;

   procedure Find (Object  : in out Ticket_Ref;
                   Session : in out ADO.Sessions.Session'Class;
                   Query   : in ADO.SQL.Query'Class;
                   Found   : out Boolean) is
      Impl  : constant Ticket_Access := new Ticket_Impl;
   begin
      Impl.Find (Session, Query, Found);
      if Found then
         ADO.Objects.Set_Object (Object, Impl.all'Access);
      else
         ADO.Objects.Set_Object (Object, null);
         Destroy (Impl);
      end if;
   end Find;

   procedure Load (Object  : in out Ticket_Ref;
                   Session : in out ADO.Sessions.Session'Class;
                   Id      : in ADO.Identifier) is
      Impl  : constant Ticket_Access := new Ticket_Impl;
      Found : Boolean;
      Query : ADO.SQL.Query;
   begin
      Query.Bind_Param (Position => 1, Value => Id);
      Query.Set_Filter ("id = ?");
      Impl.Find (Session, Query, Found);
      if not Found then
         Destroy (Impl);
         raise ADO.Objects.NOT_FOUND;
      end if;
      ADO.Objects.Set_Object (Object, Impl.all'Access);
   end Load;

   procedure Load (Object  : in out Ticket_Ref;
                   Session : in out ADO.Sessions.Session'Class;
                   Id      : in ADO.Identifier;
                   Found   : out Boolean) is
      Impl  : constant Ticket_Access := new Ticket_Impl;
      Query : ADO.SQL.Query;
   begin
      Query.Bind_Param (Position => 1, Value => Id);
      Query.Set_Filter ("id = ?");
      Impl.Find (Session, Query, Found);
      if not Found then
         Destroy (Impl);
      else
         ADO.Objects.Set_Object (Object, Impl.all'Access);
      end if;
   end Load;

   procedure Save (Object  : in out Ticket_Ref;
                   Session : in out ADO.Sessions.Master_Session'Class) is
      Impl : ADO.Objects.Object_Record_Access := Object.Get_Object;
   begin
      if Impl = null then
         Impl := new Ticket_Impl;
         ADO.Objects.Set_Object (Object, Impl);
      end if;
      if not ADO.Objects.Is_Created (Impl.all) then
         Impl.Create (Session);
      else
         Impl.Save (Session);
      end if;
   end Save;

   procedure Delete (Object  : in out Ticket_Ref;
                     Session : in out ADO.Sessions.Master_Session'Class) is
      Impl : constant ADO.Objects.Object_Record_Access := Object.Get_Object;
   begin
      if Impl /= null then
         Impl.Delete (Session);
      end if;
   end Delete;

   --  --------------------
   --  Free the object
   --  --------------------
   procedure Destroy (Object : access Ticket_Impl) is
      type Ticket_Impl_Ptr is access all Ticket_Impl;
      procedure Unchecked_Free is new Ada.Unchecked_Deallocation
              (Ticket_Impl, Ticket_Impl_Ptr);
      pragma Warnings (Off, "*redundant conversion*");
      Ptr : Ticket_Impl_Ptr := Ticket_Impl (Object.all)'Access;
      pragma Warnings (On, "*redundant conversion*");
   begin
      Unchecked_Free (Ptr);
   end Destroy;

   procedure Find (Object  : in out Ticket_Impl;
                   Session : in out ADO.Sessions.Session'Class;
                   Query   : in ADO.SQL.Query'Class;
                   Found   : out Boolean) is
      Stmt : ADO.Statements.Query_Statement
          := Session.Create_Statement (Query, TICKET_DEF'Access);
   begin
      Stmt.Execute;
      if Stmt.Has_Elements then
         Object.Load (Stmt, Session);
         Stmt.Next;
         Found := not Stmt.Has_Elements;
      else
         Found := False;
      end if;
   end Find;

   overriding
   procedure Load (Object  : in out Ticket_Impl;
                   Session : in out ADO.Sessions.Session'Class) is
      Found : Boolean;
      Query : ADO.SQL.Query;
      Id    : constant ADO.Identifier := Object.Get_Key_Value;
   begin
      Query.Bind_Param (Position => 1, Value => Id);
      Query.Set_Filter ("id = ?");
      Object.Find (Session, Query, Found);
      if not Found then
         raise ADO.Objects.NOT_FOUND;
      end if;
   end Load;

   procedure Save (Object  : in out Ticket_Impl;
                   Session : in out ADO.Sessions.Master_Session'Class) is
      Stmt : ADO.Statements.Update_Statement
         := Session.Create_Statement (TICKET_DEF'Access);
   begin
      if Object.Is_Modified (1) then
         Stmt.Save_Field (Name  => COL_0_1_NAME, --  id
                          Value => Object.Get_Key);
         Object.Clear_Modified (1);
      end if;
      if Object.Is_Modified (3) then
         Stmt.Save_Field (Name  => COL_2_1_NAME, --  summary
                          Value => Object.Summary);
         Object.Clear_Modified (3);
      end if;
      if Object.Is_Modified (4) then
         Stmt.Save_Field (Name  => COL_3_1_NAME, --  ident
                          Value => Object.Ident);
         Object.Clear_Modified (4);
      end if;
      if Object.Is_Modified (5) then
         Stmt.Save_Field (Name  => COL_4_1_NAME, --  create_date
                          Value => Object.Create_Date);
         Object.Clear_Modified (5);
      end if;
      if Object.Is_Modified (6) then
         Stmt.Save_Field (Name  => COL_5_1_NAME, --  priority
                          Value => Object.Priority);
         Object.Clear_Modified (6);
      end if;
      if Object.Is_Modified (7) then
         Stmt.Save_Field (Name  => COL_6_1_NAME, --  status
                          Value => Integer (Status_Type'Pos (Object.Status)));
         Object.Clear_Modified (7);
      end if;
      if Object.Is_Modified (8) then
         Stmt.Save_Field (Name  => COL_7_1_NAME, --  description
                          Value => Object.Description);
         Object.Clear_Modified (8);
      end if;
      if Object.Is_Modified (9) then
         Stmt.Save_Field (Name  => COL_8_1_NAME, --  update_date
                          Value => Object.Update_Date);
         Object.Clear_Modified (9);
      end if;
      if Object.Is_Modified (10) then
         Stmt.Save_Field (Name  => COL_9_1_NAME, --  ticket_type
                          Value => Integer (Ticket_Type'Pos (Object.Ticket_Type)));
         Object.Clear_Modified (10);
      end if;
      if Object.Is_Modified (11) then
         Stmt.Save_Field (Name  => COL_10_1_NAME, --  duration
                          Value => Object.Duration);
         Object.Clear_Modified (11);
      end if;
      if Object.Is_Modified (12) then
         Stmt.Save_Field (Name  => COL_11_1_NAME, --  progress
                          Value => Object.Progress);
         Object.Clear_Modified (12);
      end if;
      if Object.Is_Modified (13) then
         Stmt.Save_Field (Name  => COL_12_1_NAME, --  project_id
                          Value => Object.Project);
         Object.Clear_Modified (13);
      end if;
      if Object.Is_Modified (14) then
         Stmt.Save_Field (Name  => COL_13_1_NAME, --  creator_id
                          Value => Object.Creator);
         Object.Clear_Modified (14);
      end if;
      if Stmt.Has_Save_Fields then
         Object.Version := Object.Version + 1;
         Stmt.Save_Field (Name  => "version",
                          Value => Object.Version);
         Stmt.Set_Filter (Filter => "id = ? and version = ?");
         Stmt.Add_Param (Value => Object.Get_Key);
         Stmt.Add_Param (Value => Object.Version - 1);
         declare
            Result : Integer;
         begin
            Stmt.Execute (Result);
            if Result /= 1 then
               if Result /= 0 then
                  raise ADO.Objects.UPDATE_ERROR;
               else
                  raise ADO.Objects.LAZY_LOCK;
               end if;
            end if;
         end;
      end if;
   end Save;

   procedure Create (Object  : in out Ticket_Impl;
                     Session : in out ADO.Sessions.Master_Session'Class) is
      Query : ADO.Statements.Insert_Statement
                  := Session.Create_Statement (TICKET_DEF'Access);
      Result : Integer;
   begin
      Object.Version := 1;
      Session.Allocate (Id => Object);
      Query.Save_Field (Name  => COL_0_1_NAME, --  id
                        Value => Object.Get_Key);
      Query.Save_Field (Name  => COL_1_1_NAME, --  version
                        Value => Object.Version);
      Query.Save_Field (Name  => COL_2_1_NAME, --  summary
                        Value => Object.Summary);
      Query.Save_Field (Name  => COL_3_1_NAME, --  ident
                        Value => Object.Ident);
      Query.Save_Field (Name  => COL_4_1_NAME, --  create_date
                        Value => Object.Create_Date);
      Query.Save_Field (Name  => COL_5_1_NAME, --  priority
                        Value => Object.Priority);
      Query.Save_Field (Name  => COL_6_1_NAME, --  status
                        Value => Integer (Status_Type'Pos (Object.Status)));
      Query.Save_Field (Name  => COL_7_1_NAME, --  description
                        Value => Object.Description);
      Query.Save_Field (Name  => COL_8_1_NAME, --  update_date
                        Value => Object.Update_Date);
      Query.Save_Field (Name  => COL_9_1_NAME, --  ticket_type
                        Value => Integer (Ticket_Type'Pos (Object.Ticket_Type)));
      Query.Save_Field (Name  => COL_10_1_NAME, --  duration
                        Value => Object.Duration);
      Query.Save_Field (Name  => COL_11_1_NAME, --  progress
                        Value => Object.Progress);
      Query.Save_Field (Name  => COL_12_1_NAME, --  project_id
                        Value => Object.Project);
      Query.Save_Field (Name  => COL_13_1_NAME, --  creator_id
                        Value => Object.Creator);
      Query.Execute (Result);
      if Result /= 1 then
         raise ADO.Objects.INSERT_ERROR;
      end if;
      ADO.Objects.Set_Created (Object);
   end Create;

   procedure Delete (Object  : in out Ticket_Impl;
                     Session : in out ADO.Sessions.Master_Session'Class) is
      Stmt : ADO.Statements.Delete_Statement
         := Session.Create_Statement (TICKET_DEF'Access);
   begin
      Stmt.Set_Filter (Filter => "id = ?");
      Stmt.Add_Param (Value => Object.Get_Key);
      Stmt.Execute;
   end Delete;

   --  ------------------------------
   --  Get the bean attribute identified by the name.
   --  ------------------------------
   overriding
   function Get_Value (From : in Ticket_Ref;
                       Name : in String) return Util.Beans.Objects.Object is
      Obj  : ADO.Objects.Object_Record_Access;
      Impl : access Ticket_Impl;
   begin
      if From.Is_Null then
         return Util.Beans.Objects.Null_Object;
      end if;
      Obj := From.Get_Load_Object;
      Impl := Ticket_Impl (Obj.all)'Access;
      if Name = "id" then
         return ADO.Objects.To_Object (Impl.Get_Key);
      elsif Name = "summary" then
         return Util.Beans.Objects.To_Object (Impl.Summary);
      elsif Name = "ident" then
         return Util.Beans.Objects.To_Object (Long_Long_Integer (Impl.Ident));
      elsif Name = "create_date" then
         return Util.Beans.Objects.Time.To_Object (Impl.Create_Date);
      elsif Name = "priority" then
         return Util.Beans.Objects.To_Object (Long_Long_Integer (Impl.Priority));
      elsif Name = "status" then
         return Jason.Tickets.Models.Status_Type_Objects.To_Object (Impl.Status);
      elsif Name = "description" then
         return Util.Beans.Objects.To_Object (Impl.Description);
      elsif Name = "update_date" then
         return Util.Beans.Objects.Time.To_Object (Impl.Update_Date);
      elsif Name = "ticket_type" then
         return Jason.Tickets.Models.Ticket_Type_Objects.To_Object (Impl.Ticket_Type);
      elsif Name = "duration" then
         return Util.Beans.Objects.To_Object (Long_Long_Integer (Impl.Duration));
      elsif Name = "progress" then
         return Util.Beans.Objects.To_Object (Long_Long_Integer (Impl.Progress));
      end if;
      return Util.Beans.Objects.Null_Object;
   end Get_Value;


   procedure List (Object  : in out Ticket_Vector;
                   Session : in out ADO.Sessions.Session'Class;
                   Query   : in ADO.SQL.Query'Class) is
      Stmt : ADO.Statements.Query_Statement
        := Session.Create_Statement (Query, TICKET_DEF'Access);
   begin
      Stmt.Execute;
      Ticket_Vectors.Clear (Object);
      while Stmt.Has_Elements loop
         declare
            Item : Ticket_Ref;
            Impl : constant Ticket_Access := new Ticket_Impl;
         begin
            Impl.Load (Stmt, Session);
            ADO.Objects.Set_Object (Item, Impl.all'Access);
            Object.Append (Item);
         end;
         Stmt.Next;
      end loop;
   end List;

   --  ------------------------------
   --  Load the object from current iterator position
   --  ------------------------------
   procedure Load (Object  : in out Ticket_Impl;
                   Stmt    : in out ADO.Statements.Query_Statement'Class;
                   Session : in out ADO.Sessions.Session'Class) is
   begin
      Object.Set_Key_Value (Stmt.Get_Identifier (0));
      Object.Summary := Stmt.Get_Unbounded_String (2);
      Object.Ident := Stmt.Get_Integer (3);
      Object.Create_Date := Stmt.Get_Time (4);
      Object.Priority := Stmt.Get_Integer (5);
      Object.Status := Status_Type'Val (Stmt.Get_Integer (6));
      Object.Description := Stmt.Get_Unbounded_String (7);
      Object.Update_Date := Stmt.Get_Time (8);
      Object.Ticket_Type := Ticket_Type'Val (Stmt.Get_Integer (9));
      Object.Duration := Stmt.Get_Integer (10);
      Object.Progress := Stmt.Get_Integer (11);
      if not Stmt.Is_Null (12) then
         Object.Project.Set_Key_Value (Stmt.Get_Identifier (12), Session);
      end if;
      if not Stmt.Is_Null (13) then
         Object.Creator.Set_Key_Value (Stmt.Get_Identifier (13), Session);
      end if;
      Object.Version := Stmt.Get_Integer (1);
      ADO.Objects.Set_Created (Object);
   end Load;
   function Attribute_Key (Id : in ADO.Identifier) return ADO.Objects.Object_Key is
      Result : ADO.Objects.Object_Key (Of_Type  => ADO.Objects.KEY_INTEGER,
                                       Of_Class => ATTRIBUTE_DEF'Access);
   begin
      ADO.Objects.Set_Value (Result, Id);
      return Result;
   end Attribute_Key;

   function Attribute_Key (Id : in String) return ADO.Objects.Object_Key is
      Result : ADO.Objects.Object_Key (Of_Type  => ADO.Objects.KEY_INTEGER,
                                       Of_Class => ATTRIBUTE_DEF'Access);
   begin
      ADO.Objects.Set_Value (Result, Id);
      return Result;
   end Attribute_Key;

   function "=" (Left, Right : Attribute_Ref'Class) return Boolean is
   begin
      return ADO.Objects.Object_Ref'Class (Left) = ADO.Objects.Object_Ref'Class (Right);
   end "=";

   procedure Set_Field (Object : in out Attribute_Ref'Class;
                        Impl   : out Attribute_Access) is
      Result : ADO.Objects.Object_Record_Access;
   begin
      Object.Prepare_Modify (Result);
      Impl := Attribute_Impl (Result.all)'Access;
   end Set_Field;

   --  Internal method to allocate the Object_Record instance
   procedure Allocate (Object : in out Attribute_Ref) is
      Impl : Attribute_Access;
   begin
      Impl := new Attribute_Impl;
      Impl.Version := 0;
      ADO.Objects.Set_Object (Object, Impl.all'Access);
   end Allocate;

   -- ----------------------------------------
   --  Data object: Attribute
   -- ----------------------------------------

   procedure Set_Id (Object : in out Attribute_Ref;
                     Value  : in ADO.Identifier) is
      Impl : Attribute_Access;
   begin
      Set_Field (Object, Impl);
      ADO.Objects.Set_Field_Key_Value (Impl.all, 1, Value);
   end Set_Id;

   function Get_Id (Object : in Attribute_Ref)
                  return ADO.Identifier is
      Impl : constant Attribute_Access
         := Attribute_Impl (Object.Get_Object.all)'Access;
   begin
      return Impl.Get_Key_Value;
   end Get_Id;


   procedure Set_Value (Object : in out Attribute_Ref;
                         Value : in String) is
      Impl : Attribute_Access;
   begin
      Set_Field (Object, Impl);
      ADO.Objects.Set_Field_String (Impl.all, 2, Impl.Value, Value);
   end Set_Value;

   procedure Set_Value (Object : in out Attribute_Ref;
                        Value  : in Ada.Strings.Unbounded.Unbounded_String) is
      Impl : Attribute_Access;
   begin
      Set_Field (Object, Impl);
      ADO.Objects.Set_Field_Unbounded_String (Impl.all, 2, Impl.Value, Value);
   end Set_Value;

   function Get_Value (Object : in Attribute_Ref)
                 return String is
   begin
      return Ada.Strings.Unbounded.To_String (Object.Get_Value);
   end Get_Value;
   function Get_Value (Object : in Attribute_Ref)
                  return Ada.Strings.Unbounded.Unbounded_String is
      Impl : constant Attribute_Access
         := Attribute_Impl (Object.Get_Load_Object.all)'Access;
   begin
      return Impl.Value;
   end Get_Value;


   function Get_Version (Object : in Attribute_Ref)
                  return Integer is
      Impl : constant Attribute_Access
         := Attribute_Impl (Object.Get_Load_Object.all)'Access;
   begin
      return Impl.Version;
   end Get_Version;


   procedure Set_Definition (Object : in out Attribute_Ref;
                             Value  : in Jason.Projects.Models.Attribute_Definition_Ref'Class) is
      Impl : Attribute_Access;
   begin
      Set_Field (Object, Impl);
      ADO.Objects.Set_Field_Object (Impl.all, 4, Impl.Definition, Value);
   end Set_Definition;

   function Get_Definition (Object : in Attribute_Ref)
                  return Jason.Projects.Models.Attribute_Definition_Ref'Class is
      Impl : constant Attribute_Access
         := Attribute_Impl (Object.Get_Load_Object.all)'Access;
   begin
      return Impl.Definition;
   end Get_Definition;


   procedure Set_Ticket (Object : in out Attribute_Ref;
                         Value  : in Jason.Tickets.Models.Ticket_Ref'Class) is
      Impl : Attribute_Access;
   begin
      Set_Field (Object, Impl);
      ADO.Objects.Set_Field_Object (Impl.all, 5, Impl.Ticket, Value);
   end Set_Ticket;

   function Get_Ticket (Object : in Attribute_Ref)
                  return Jason.Tickets.Models.Ticket_Ref'Class is
      Impl : constant Attribute_Access
         := Attribute_Impl (Object.Get_Load_Object.all)'Access;
   begin
      return Impl.Ticket;
   end Get_Ticket;

   --  Copy of the object.
   procedure Copy (Object : in Attribute_Ref;
                   Into   : in out Attribute_Ref) is
      Result : Attribute_Ref;
   begin
      if not Object.Is_Null then
         declare
            Impl : constant Attribute_Access
              := Attribute_Impl (Object.Get_Load_Object.all)'Access;
            Copy : constant Attribute_Access
              := new Attribute_Impl;
         begin
            ADO.Objects.Set_Object (Result, Copy.all'Access);
            Copy.Copy (Impl.all);
            Copy.Value := Impl.Value;
            Copy.Version := Impl.Version;
            Copy.Definition := Impl.Definition;
            Copy.Ticket := Impl.Ticket;
         end;
      end if;
      Into := Result;
   end Copy;

   procedure Find (Object  : in out Attribute_Ref;
                   Session : in out ADO.Sessions.Session'Class;
                   Query   : in ADO.SQL.Query'Class;
                   Found   : out Boolean) is
      Impl  : constant Attribute_Access := new Attribute_Impl;
   begin
      Impl.Find (Session, Query, Found);
      if Found then
         ADO.Objects.Set_Object (Object, Impl.all'Access);
      else
         ADO.Objects.Set_Object (Object, null);
         Destroy (Impl);
      end if;
   end Find;

   procedure Load (Object  : in out Attribute_Ref;
                   Session : in out ADO.Sessions.Session'Class;
                   Id      : in ADO.Identifier) is
      Impl  : constant Attribute_Access := new Attribute_Impl;
      Found : Boolean;
      Query : ADO.SQL.Query;
   begin
      Query.Bind_Param (Position => 1, Value => Id);
      Query.Set_Filter ("id = ?");
      Impl.Find (Session, Query, Found);
      if not Found then
         Destroy (Impl);
         raise ADO.Objects.NOT_FOUND;
      end if;
      ADO.Objects.Set_Object (Object, Impl.all'Access);
   end Load;

   procedure Load (Object  : in out Attribute_Ref;
                   Session : in out ADO.Sessions.Session'Class;
                   Id      : in ADO.Identifier;
                   Found   : out Boolean) is
      Impl  : constant Attribute_Access := new Attribute_Impl;
      Query : ADO.SQL.Query;
   begin
      Query.Bind_Param (Position => 1, Value => Id);
      Query.Set_Filter ("id = ?");
      Impl.Find (Session, Query, Found);
      if not Found then
         Destroy (Impl);
      else
         ADO.Objects.Set_Object (Object, Impl.all'Access);
      end if;
   end Load;

   procedure Save (Object  : in out Attribute_Ref;
                   Session : in out ADO.Sessions.Master_Session'Class) is
      Impl : ADO.Objects.Object_Record_Access := Object.Get_Object;
   begin
      if Impl = null then
         Impl := new Attribute_Impl;
         ADO.Objects.Set_Object (Object, Impl);
      end if;
      if not ADO.Objects.Is_Created (Impl.all) then
         Impl.Create (Session);
      else
         Impl.Save (Session);
      end if;
   end Save;

   procedure Delete (Object  : in out Attribute_Ref;
                     Session : in out ADO.Sessions.Master_Session'Class) is
      Impl : constant ADO.Objects.Object_Record_Access := Object.Get_Object;
   begin
      if Impl /= null then
         Impl.Delete (Session);
      end if;
   end Delete;

   --  --------------------
   --  Free the object
   --  --------------------
   procedure Destroy (Object : access Attribute_Impl) is
      type Attribute_Impl_Ptr is access all Attribute_Impl;
      procedure Unchecked_Free is new Ada.Unchecked_Deallocation
              (Attribute_Impl, Attribute_Impl_Ptr);
      pragma Warnings (Off, "*redundant conversion*");
      Ptr : Attribute_Impl_Ptr := Attribute_Impl (Object.all)'Access;
      pragma Warnings (On, "*redundant conversion*");
   begin
      Unchecked_Free (Ptr);
   end Destroy;

   procedure Find (Object  : in out Attribute_Impl;
                   Session : in out ADO.Sessions.Session'Class;
                   Query   : in ADO.SQL.Query'Class;
                   Found   : out Boolean) is
      Stmt : ADO.Statements.Query_Statement
          := Session.Create_Statement (Query, ATTRIBUTE_DEF'Access);
   begin
      Stmt.Execute;
      if Stmt.Has_Elements then
         Object.Load (Stmt, Session);
         Stmt.Next;
         Found := not Stmt.Has_Elements;
      else
         Found := False;
      end if;
   end Find;

   overriding
   procedure Load (Object  : in out Attribute_Impl;
                   Session : in out ADO.Sessions.Session'Class) is
      Found : Boolean;
      Query : ADO.SQL.Query;
      Id    : constant ADO.Identifier := Object.Get_Key_Value;
   begin
      Query.Bind_Param (Position => 1, Value => Id);
      Query.Set_Filter ("id = ?");
      Object.Find (Session, Query, Found);
      if not Found then
         raise ADO.Objects.NOT_FOUND;
      end if;
   end Load;

   procedure Save (Object  : in out Attribute_Impl;
                   Session : in out ADO.Sessions.Master_Session'Class) is
      Stmt : ADO.Statements.Update_Statement
         := Session.Create_Statement (ATTRIBUTE_DEF'Access);
   begin
      if Object.Is_Modified (1) then
         Stmt.Save_Field (Name  => COL_0_2_NAME, --  id
                          Value => Object.Get_Key);
         Object.Clear_Modified (1);
      end if;
      if Object.Is_Modified (2) then
         Stmt.Save_Field (Name  => COL_1_2_NAME, --  value
                          Value => Object.Value);
         Object.Clear_Modified (2);
      end if;
      if Object.Is_Modified (4) then
         Stmt.Save_Field (Name  => COL_3_2_NAME, --  definition_id
                          Value => Object.Definition);
         Object.Clear_Modified (4);
      end if;
      if Object.Is_Modified (5) then
         Stmt.Save_Field (Name  => COL_4_2_NAME, --  ticket_id
                          Value => Object.Ticket);
         Object.Clear_Modified (5);
      end if;
      if Stmt.Has_Save_Fields then
         Object.Version := Object.Version + 1;
         Stmt.Save_Field (Name  => "version",
                          Value => Object.Version);
         Stmt.Set_Filter (Filter => "id = ? and version = ?");
         Stmt.Add_Param (Value => Object.Get_Key);
         Stmt.Add_Param (Value => Object.Version - 1);
         declare
            Result : Integer;
         begin
            Stmt.Execute (Result);
            if Result /= 1 then
               if Result /= 0 then
                  raise ADO.Objects.UPDATE_ERROR;
               else
                  raise ADO.Objects.LAZY_LOCK;
               end if;
            end if;
         end;
      end if;
   end Save;

   procedure Create (Object  : in out Attribute_Impl;
                     Session : in out ADO.Sessions.Master_Session'Class) is
      Query : ADO.Statements.Insert_Statement
                  := Session.Create_Statement (ATTRIBUTE_DEF'Access);
      Result : Integer;
   begin
      Object.Version := 1;
      Session.Allocate (Id => Object);
      Query.Save_Field (Name  => COL_0_2_NAME, --  id
                        Value => Object.Get_Key);
      Query.Save_Field (Name  => COL_1_2_NAME, --  value
                        Value => Object.Value);
      Query.Save_Field (Name  => COL_2_2_NAME, --  version
                        Value => Object.Version);
      Query.Save_Field (Name  => COL_3_2_NAME, --  definition_id
                        Value => Object.Definition);
      Query.Save_Field (Name  => COL_4_2_NAME, --  ticket_id
                        Value => Object.Ticket);
      Query.Execute (Result);
      if Result /= 1 then
         raise ADO.Objects.INSERT_ERROR;
      end if;
      ADO.Objects.Set_Created (Object);
   end Create;

   procedure Delete (Object  : in out Attribute_Impl;
                     Session : in out ADO.Sessions.Master_Session'Class) is
      Stmt : ADO.Statements.Delete_Statement
         := Session.Create_Statement (ATTRIBUTE_DEF'Access);
   begin
      Stmt.Set_Filter (Filter => "id = ?");
      Stmt.Add_Param (Value => Object.Get_Key);
      Stmt.Execute;
   end Delete;

   --  ------------------------------
   --  Get the bean attribute identified by the name.
   --  ------------------------------
   overriding
   function Get_Value (From : in Attribute_Ref;
                       Name : in String) return Util.Beans.Objects.Object is
      Obj  : ADO.Objects.Object_Record_Access;
      Impl : access Attribute_Impl;
   begin
      if From.Is_Null then
         return Util.Beans.Objects.Null_Object;
      end if;
      Obj := From.Get_Load_Object;
      Impl := Attribute_Impl (Obj.all)'Access;
      if Name = "id" then
         return ADO.Objects.To_Object (Impl.Get_Key);
      elsif Name = "value" then
         return Util.Beans.Objects.To_Object (Impl.Value);
      end if;
      return Util.Beans.Objects.Null_Object;
   end Get_Value;


   procedure List (Object  : in out Attribute_Vector;
                   Session : in out ADO.Sessions.Session'Class;
                   Query   : in ADO.SQL.Query'Class) is
      Stmt : ADO.Statements.Query_Statement
        := Session.Create_Statement (Query, ATTRIBUTE_DEF'Access);
   begin
      Stmt.Execute;
      Attribute_Vectors.Clear (Object);
      while Stmt.Has_Elements loop
         declare
            Item : Attribute_Ref;
            Impl : constant Attribute_Access := new Attribute_Impl;
         begin
            Impl.Load (Stmt, Session);
            ADO.Objects.Set_Object (Item, Impl.all'Access);
            Object.Append (Item);
         end;
         Stmt.Next;
      end loop;
   end List;

   --  ------------------------------
   --  Load the object from current iterator position
   --  ------------------------------
   procedure Load (Object  : in out Attribute_Impl;
                   Stmt    : in out ADO.Statements.Query_Statement'Class;
                   Session : in out ADO.Sessions.Session'Class) is
   begin
      Object.Set_Key_Value (Stmt.Get_Identifier (0));
      Object.Value := Stmt.Get_Unbounded_String (1);
      if not Stmt.Is_Null (3) then
         Object.Definition.Set_Key_Value (Stmt.Get_Identifier (3), Session);
      end if;
      if not Stmt.Is_Null (4) then
         Object.Ticket.Set_Key_Value (Stmt.Get_Identifier (4), Session);
      end if;
      Object.Version := Stmt.Get_Integer (2);
      ADO.Objects.Set_Created (Object);
   end Load;


   --  ------------------------------
   --  Get the bean attribute identified by the name.
   --  ------------------------------
   overriding
   function Get_Value (From : in List_Info;
                       Name : in String) return Util.Beans.Objects.Object is
   begin
      if Name = "id" then
         return Util.Beans.Objects.To_Object (Long_Long_Integer (From.Id));
      elsif Name = "ident" then
         return Util.Beans.Objects.To_Object (Long_Long_Integer (From.Ident));
      elsif Name = "summary" then
         return Util.Beans.Objects.To_Object (From.Summary);
      elsif Name = "priority" then
         return Util.Beans.Objects.To_Object (Long_Long_Integer (From.Priority));
      elsif Name = "create_date" then
         return Util.Beans.Objects.Time.To_Object (From.Create_Date);
      elsif Name = "update_date" then
         return Util.Beans.Objects.Time.To_Object (From.Update_Date);
      elsif Name = "status" then
         return Jason.Tickets.Models.Status_Type_Objects.To_Object (From.Status);
      elsif Name = "ticket_type" then
         return Jason.Tickets.Models.Ticket_Type_Objects.To_Object (From.Ticket_Type);
      elsif Name = "duration" then
         return Util.Beans.Objects.To_Object (Long_Long_Integer (From.Duration));
      elsif Name = "progress" then
         return Util.Beans.Objects.To_Object (Long_Long_Integer (From.Progress));
      elsif Name = "creator" then
         return Util.Beans.Objects.To_Object (From.Creator);
      end if;
      return Util.Beans.Objects.Null_Object;
   end Get_Value;


   --  ------------------------------
   --  Set the value identified by the name
   --  ------------------------------
   overriding
   procedure Set_Value (Item  : in out List_Info;
                        Name  : in String;
                        Value : in Util.Beans.Objects.Object) is
   begin
      if Name = "id" then
         Item.Id := ADO.Identifier (Util.Beans.Objects.To_Long_Long_Integer (Value));
      elsif Name = "ident" then
         Item.Ident := Util.Beans.Objects.To_Integer (Value);
      elsif Name = "summary" then
         Item.Summary := Util.Beans.Objects.To_Unbounded_String (Value);
      elsif Name = "priority" then
         Item.Priority := Util.Beans.Objects.To_Integer (Value);
      elsif Name = "create_date" then
         Item.Create_Date := Util.Beans.Objects.Time.To_Time (Value);
      elsif Name = "update_date" then
         Item.Update_Date := Util.Beans.Objects.Time.To_Time (Value);
      elsif Name = "status" then
         Item.Status := Jason.Tickets.Models.Status_Type_Objects.To_Value (Value);
      elsif Name = "ticket_type" then
         Item.Ticket_Type := Jason.Tickets.Models.Ticket_Type_Objects.To_Value (Value);
      elsif Name = "duration" then
         Item.Duration := Util.Beans.Objects.To_Integer (Value);
      elsif Name = "progress" then
         Item.Progress := Util.Beans.Objects.To_Integer (Value);
      elsif Name = "creator" then
         Item.Creator := Util.Beans.Objects.To_Unbounded_String (Value);
      end if;
   end Set_Value;


   --  --------------------
   --  Run the query controlled by <b>Context</b> and append the list in <b>Object</b>.
   --  --------------------
   procedure List (Object  : in out List_Info_List_Bean'Class;
                   Session : in out ADO.Sessions.Session'Class;
                   Context : in out ADO.Queries.Context'Class) is
   begin
      List (Object.List, Session, Context);
   end List;

   --  --------------------
   --  The list of tickets.
   --  --------------------
   procedure List (Object  : in out List_Info_Vector;
                   Session : in out ADO.Sessions.Session'Class;
                   Context : in out ADO.Queries.Context'Class) is
      procedure Read (Into : in out List_Info);

      Stmt : ADO.Statements.Query_Statement
          := Session.Create_Statement (Context);
      Pos  : Positive := 1;
      procedure Read (Into : in out List_Info) is
      begin
         Into.Id := Stmt.Get_Identifier (0);
         Into.Ident := Stmt.Get_Integer (1);
         Into.Summary := Stmt.Get_Unbounded_String (2);
         Into.Priority := Stmt.Get_Integer (3);
         Into.Create_Date := Stmt.Get_Time (4);
         Into.Update_Date := Stmt.Get_Time (5);
         Into.Status := Jason.Tickets.Models.Status_Type'Val (Stmt.Get_Integer (6));
         Into.Ticket_Type := Jason.Tickets.Models.Ticket_Type'Val (Stmt.Get_Integer (7));
         Into.Duration := Stmt.Get_Integer (8);
         Into.Progress := Stmt.Get_Integer (9);
         Into.Creator := Stmt.Get_Unbounded_String (10);
      end Read;
   begin
      Stmt.Execute;
      List_Info_Vectors.Clear (Object);
      while Stmt.Has_Elements loop
         Object.Insert_Space (Before => Pos);
         Object.Update_Element (Index => Pos, Process => Read'Access);
         Pos := Pos + 1;
         Stmt.Next;
      end loop;
   end List;

   procedure Op_Load (Bean    : in out Ticket_Info;
                      Outcome : in out Ada.Strings.Unbounded.Unbounded_String);
   procedure Op_Load (Bean    : in out Ticket_Info;
                      Outcome : in out Ada.Strings.Unbounded.Unbounded_String) is
   begin
      Ticket_Info'Class (Bean).Load (Outcome);
   end Op_Load;
   package Binding_Ticket_Info_1 is
     new ASF.Events.Faces.Actions.Action_Method.Bind (Bean   => Ticket_Info,
                                                      Method => Op_Load,
                                                      Name   => "load");

   Binding_Ticket_Info_Array : aliased constant Util.Beans.Methods.Method_Binding_Array
     := (1 => Binding_Ticket_Info_1.Proxy'Access
     );

   --  ------------------------------
   --  This bean provides some methods that can be used in a Method_Expression.
   --  ------------------------------
   overriding
   function Get_Method_Bindings (From : in Ticket_Info)
                                 return Util.Beans.Methods.Method_Binding_Array_Access is
      pragma Unreferenced (From);
   begin
      return Binding_Ticket_Info_Array'Access;
   end Get_Method_Bindings;
   --  ------------------------------
   --  Get the bean attribute identified by the name.
   --  ------------------------------
   overriding
   function Get_Value (From : in Ticket_Info;
                       Name : in String) return Util.Beans.Objects.Object is
   begin
      if Name = "id" then
         return Util.Beans.Objects.To_Object (Long_Long_Integer (From.Id));
      elsif Name = "ident" then
         return Util.Beans.Objects.To_Object (Long_Long_Integer (From.Ident));
      elsif Name = "summary" then
         return Util.Beans.Objects.To_Object (From.Summary);
      elsif Name = "description" then
         return Util.Beans.Objects.To_Object (From.Description);
      elsif Name = "priority" then
         return Util.Beans.Objects.To_Object (Long_Long_Integer (From.Priority));
      elsif Name = "create_date" then
         return Util.Beans.Objects.Time.To_Object (From.Create_Date);
      elsif Name = "update_date" then
         return Util.Beans.Objects.Time.To_Object (From.Update_Date);
      elsif Name = "status" then
         return Jason.Tickets.Models.Status_Type_Objects.To_Object (From.Status);
      elsif Name = "project_id" then
         return Util.Beans.Objects.To_Object (Long_Long_Integer (From.Project_Id));
      elsif Name = "project_name" then
         return Util.Beans.Objects.To_Object (From.Project_Name);
      elsif Name = "creator" then
         return Util.Beans.Objects.To_Object (From.Creator);
      end if;
      return Util.Beans.Objects.Null_Object;
   end Get_Value;


   --  ------------------------------
   --  Set the value identified by the name
   --  ------------------------------
   overriding
   procedure Set_Value (Item  : in out Ticket_Info;
                        Name  : in String;
                        Value : in Util.Beans.Objects.Object) is
   begin
      if Name = "id" then
         Item.Id := ADO.Identifier (Util.Beans.Objects.To_Long_Long_Integer (Value));
      elsif Name = "ident" then
         Item.Ident := Util.Beans.Objects.To_Integer (Value);
      elsif Name = "summary" then
         Item.Summary := Util.Beans.Objects.To_Unbounded_String (Value);
      elsif Name = "description" then
         Item.Description := Util.Beans.Objects.To_Unbounded_String (Value);
      elsif Name = "priority" then
         Item.Priority := Util.Beans.Objects.To_Integer (Value);
      elsif Name = "create_date" then
         Item.Create_Date := Util.Beans.Objects.Time.To_Time (Value);
      elsif Name = "update_date" then
         Item.Update_Date := Util.Beans.Objects.Time.To_Time (Value);
      elsif Name = "status" then
         Item.Status := Jason.Tickets.Models.Status_Type_Objects.To_Value (Value);
      elsif Name = "project_id" then
         Item.Project_Id := ADO.Identifier (Util.Beans.Objects.To_Long_Long_Integer (Value));
      elsif Name = "project_name" then
         Item.Project_Name := Util.Beans.Objects.To_Unbounded_String (Value);
      elsif Name = "creator" then
         Item.Creator := Util.Beans.Objects.To_Unbounded_String (Value);
      end if;
   end Set_Value;


   --  --------------------
   --  Read in the object the data from the query result and prepare to read the next row.
   --  If there is no row, raise the ADO.NOT_FOUND exception.
   --  --------------------
   procedure Read (Into : in out Ticket_Info;
                   Stmt : in out ADO.Statements.Query_Statement'Class) is
   begin
      if not Stmt.Has_Elements then
         raise ADO.Objects.NOT_FOUND;
      end if;
      Into.Id := Stmt.Get_Identifier (0);
      Into.Ident := Stmt.Get_Integer (1);
      Into.Summary := Stmt.Get_Unbounded_String (2);
      Into.Description := Stmt.Get_Unbounded_String (3);
      Into.Priority := Stmt.Get_Integer (4);
      Into.Create_Date := Stmt.Get_Time (5);
      Into.Update_Date := Stmt.Get_Time (6);
      Into.Status := Jason.Tickets.Models.Status_Type'Val (Stmt.Get_Integer (7));
      Into.Project_Id := Stmt.Get_Identifier (8);
      Into.Project_Name := Stmt.Get_Unbounded_String (9);
      Into.Creator := Stmt.Get_Unbounded_String (10);
      Stmt.Next;
   end Read;

   --  --------------------
   --  Run the query controlled by <b>Context</b> and load the result in <b>Object</b>.
   --  --------------------
   procedure Load (Object  : in out Ticket_Info'Class;
                   Session : in out ADO.Sessions.Session'Class;
                   Context : in out ADO.Queries.Context'Class) is
      Stmt : ADO.Statements.Query_Statement := Session.Create_Statement (Context);
   begin
      Stmt.Execute;
      Read (Object, Stmt);
      if Stmt.Has_Elements then
         raise ADO.Objects.NOT_FOUND;
      end if;
   end Load;

   procedure Op_Load (Bean    : in out Ticket_Bean;
                      Outcome : in out Ada.Strings.Unbounded.Unbounded_String);
   procedure Op_Load (Bean    : in out Ticket_Bean;
                      Outcome : in out Ada.Strings.Unbounded.Unbounded_String) is
   begin
      Ticket_Bean'Class (Bean).Load (Outcome);
   end Op_Load;
   package Binding_Ticket_Bean_1 is
     new ASF.Events.Faces.Actions.Action_Method.Bind (Bean   => Ticket_Bean,
                                                      Method => Op_Load,
                                                      Name   => "load");
   procedure Op_Create (Bean    : in out Ticket_Bean;
                        Outcome : in out Ada.Strings.Unbounded.Unbounded_String);
   procedure Op_Create (Bean    : in out Ticket_Bean;
                        Outcome : in out Ada.Strings.Unbounded.Unbounded_String) is
   begin
      Ticket_Bean'Class (Bean).Create (Outcome);
   end Op_Create;
   package Binding_Ticket_Bean_2 is
     new ASF.Events.Faces.Actions.Action_Method.Bind (Bean   => Ticket_Bean,
                                                      Method => Op_Create,
                                                      Name   => "create");
   procedure Op_Save (Bean    : in out Ticket_Bean;
                      Outcome : in out Ada.Strings.Unbounded.Unbounded_String);
   procedure Op_Save (Bean    : in out Ticket_Bean;
                      Outcome : in out Ada.Strings.Unbounded.Unbounded_String) is
   begin
      Ticket_Bean'Class (Bean).Save (Outcome);
   end Op_Save;
   package Binding_Ticket_Bean_3 is
     new ASF.Events.Faces.Actions.Action_Method.Bind (Bean   => Ticket_Bean,
                                                      Method => Op_Save,
                                                      Name   => "save");
   procedure Op_Save_Status (Bean    : in out Ticket_Bean;
                             Outcome : in out Ada.Strings.Unbounded.Unbounded_String);
   procedure Op_Save_Status (Bean    : in out Ticket_Bean;
                             Outcome : in out Ada.Strings.Unbounded.Unbounded_String) is
   begin
      Ticket_Bean'Class (Bean).Save_Status (Outcome);
   end Op_Save_Status;
   package Binding_Ticket_Bean_4 is
     new ASF.Events.Faces.Actions.Action_Method.Bind (Bean   => Ticket_Bean,
                                                      Method => Op_Save_Status,
                                                      Name   => "save_status");

   Binding_Ticket_Bean_Array : aliased constant Util.Beans.Methods.Method_Binding_Array
     := (1 => Binding_Ticket_Bean_1.Proxy'Access,
         2 => Binding_Ticket_Bean_2.Proxy'Access,
         3 => Binding_Ticket_Bean_3.Proxy'Access,
         4 => Binding_Ticket_Bean_4.Proxy'Access
     );

   --  ------------------------------
   --  This bean provides some methods that can be used in a Method_Expression.
   --  ------------------------------
   overriding
   function Get_Method_Bindings (From : in Ticket_Bean)
                                 return Util.Beans.Methods.Method_Binding_Array_Access is
      pragma Unreferenced (From);
   begin
      return Binding_Ticket_Bean_Array'Access;
   end Get_Method_Bindings;
   --  ------------------------------
   --  Get the bean attribute identified by the name.
   --  ------------------------------
   overriding
   function Get_Value (From : in Ticket_Bean;
                       Name : in String) return Util.Beans.Objects.Object is
   begin
      if Name = "comment" then
         return Util.Beans.Objects.To_Object (From.Comment);
      end if;
      return Jason.Tickets.Models.Ticket_Ref (From).Get_Value (Name);
   end Get_Value;


   --  ------------------------------
   --  Set the value identified by the name
   --  ------------------------------
   overriding
   procedure Set_Value (Item  : in out Ticket_Bean;
                        Name  : in String;
                        Value : in Util.Beans.Objects.Object) is
   begin
      if Name = "comment" then
         Item.Comment := Util.Beans.Objects.To_Unbounded_String (Value);
      elsif Name = "summary" then
         Item.Set_Summary (Util.Beans.Objects.To_String (Value));
      elsif Name = "ident" then
         Item.Set_Ident (Util.Beans.Objects.To_Integer (Value));
      elsif Name = "create_date" then
         Item.Set_Create_Date (Util.Beans.Objects.Time.To_Time (Value));
      elsif Name = "priority" then
         Item.Set_Priority (Util.Beans.Objects.To_Integer (Value));
      elsif Name = "status" then
         Item.Set_Status (Status_Type_Objects.To_Value (Value));
      elsif Name = "description" then
         Item.Set_Description (Util.Beans.Objects.To_String (Value));
      elsif Name = "update_date" then
         Item.Set_Update_Date (Util.Beans.Objects.Time.To_Time (Value));
      elsif Name = "ticket_type" then
         Item.Set_Ticket_Type (Ticket_Type_Objects.To_Value (Value));
      elsif Name = "duration" then
         Item.Set_Duration (Util.Beans.Objects.To_Integer (Value));
      elsif Name = "progress" then
         Item.Set_Progress (Util.Beans.Objects.To_Integer (Value));
      end if;
   end Set_Value;

   procedure Op_Load (Bean    : in out Ticket_List_Bean;
                      Outcome : in out Ada.Strings.Unbounded.Unbounded_String);
   procedure Op_Load (Bean    : in out Ticket_List_Bean;
                      Outcome : in out Ada.Strings.Unbounded.Unbounded_String) is
   begin
      Ticket_List_Bean'Class (Bean).Load (Outcome);
   end Op_Load;
   package Binding_Ticket_List_Bean_1 is
     new ASF.Events.Faces.Actions.Action_Method.Bind (Bean   => Ticket_List_Bean,
                                                      Method => Op_Load,
                                                      Name   => "load");

   Binding_Ticket_List_Bean_Array : aliased constant Util.Beans.Methods.Method_Binding_Array
     := (1 => Binding_Ticket_List_Bean_1.Proxy'Access
     );

   --  ------------------------------
   --  This bean provides some methods that can be used in a Method_Expression.
   --  ------------------------------
   overriding
   function Get_Method_Bindings (From : in Ticket_List_Bean)
                                 return Util.Beans.Methods.Method_Binding_Array_Access is
      pragma Unreferenced (From);
   begin
      return Binding_Ticket_List_Bean_Array'Access;
   end Get_Method_Bindings;
   --  ------------------------------
   --  Get the bean attribute identified by the name.
   --  ------------------------------
   overriding
   function Get_Value (From : in Ticket_List_Bean;
                       Name : in String) return Util.Beans.Objects.Object is
   begin
      if Name = "project_id" then
         return Util.Beans.Objects.To_Object (Long_Long_Integer (From.Project_Id));
      elsif Name = "page" then
         return Util.Beans.Objects.To_Object (Long_Long_Integer (From.Page));
      elsif Name = "count" then
         return Util.Beans.Objects.To_Object (Long_Long_Integer (From.Count));
      elsif Name = "tag" then
         return Util.Beans.Objects.To_Object (From.Tag);
      elsif Name = "page_size" then
         return Util.Beans.Objects.To_Object (Long_Long_Integer (From.Page_Size));
      elsif Name = "sort" then
         return Util.Beans.Objects.To_Object (From.Sort);
      elsif Name = "status" then
         return Status_Type_Objects.To_Object (From.Status);
      elsif Name = "priority" then
         return Util.Beans.Objects.To_Object (Long_Long_Integer (From.Priority));
      elsif Name = "ticket_kind" then
         return Ticket_Type_Objects.To_Object (From.Ticket_Kind);
      end if;
      return Util.Beans.Objects.Null_Object;
   end Get_Value;


   --  ------------------------------
   --  Set the value identified by the name
   --  ------------------------------
   overriding
   procedure Set_Value (Item  : in out Ticket_List_Bean;
                        Name  : in String;
                        Value : in Util.Beans.Objects.Object) is
   begin
      if Name = "project_id" then
         Item.Project_Id := ADO.Identifier (Util.Beans.Objects.To_Long_Long_Integer (Value));
      elsif Name = "page" then
         Item.Page := Util.Beans.Objects.To_Integer (Value);
      elsif Name = "count" then
         Item.Count := Util.Beans.Objects.To_Integer (Value);
      elsif Name = "tag" then
         Item.Tag := Util.Beans.Objects.To_Unbounded_String (Value);
      elsif Name = "page_size" then
         Item.Page_Size := Util.Beans.Objects.To_Integer (Value);
      elsif Name = "sort" then
         Item.Sort := Util.Beans.Objects.To_Unbounded_String (Value);
      elsif Name = "status" then
         Item.Status := Status_Type_Objects.To_Value (Value);
      elsif Name = "priority" then
         Item.Priority := Util.Beans.Objects.To_Integer (Value);
      elsif Name = "ticket_kind" then
         Item.Ticket_Kind := Ticket_Type_Objects.To_Value (Value);
      end if;
   end Set_Value;

   procedure Op_Load (Bean    : in out Ticket_Info_Bean;
                      Outcome : in out Ada.Strings.Unbounded.Unbounded_String);
   procedure Op_Load (Bean    : in out Ticket_Info_Bean;
                      Outcome : in out Ada.Strings.Unbounded.Unbounded_String) is
   begin
      Ticket_Info_Bean'Class (Bean).Load (Outcome);
   end Op_Load;
   package Binding_Ticket_Info_Bean_1 is
     new ASF.Events.Faces.Actions.Action_Method.Bind (Bean   => Ticket_Info_Bean,
                                                      Method => Op_Load,
                                                      Name   => "load");

   Binding_Ticket_Info_Bean_Array : aliased constant Util.Beans.Methods.Method_Binding_Array
     := (1 => Binding_Ticket_Info_Bean_1.Proxy'Access
     );

   --  ------------------------------
   --  This bean provides some methods that can be used in a Method_Expression.
   --  ------------------------------
   overriding
   function Get_Method_Bindings (From : in Ticket_Info_Bean)
                                 return Util.Beans.Methods.Method_Binding_Array_Access is
      pragma Unreferenced (From);
   begin
      return Binding_Ticket_Info_Bean_Array'Access;
   end Get_Method_Bindings;
   --  ------------------------------
   --  Get the bean attribute identified by the name.
   --  ------------------------------
   overriding
   function Get_Value (From : in Ticket_Info_Bean;
                       Name : in String) return Util.Beans.Objects.Object is
   begin
      if Name = "ticket_id" then
         return Util.Beans.Objects.To_Object (Long_Long_Integer (From.Ticket_Id));
      end if;
      return Util.Beans.Objects.Null_Object;
   end Get_Value;


   --  ------------------------------
   --  Set the value identified by the name
   --  ------------------------------
   overriding
   procedure Set_Value (Item  : in out Ticket_Info_Bean;
                        Name  : in String;
                        Value : in Util.Beans.Objects.Object) is
   begin
      if Name = "ticket_id" then
         Item.Ticket_Id := ADO.Identifier (Util.Beans.Objects.To_Long_Long_Integer (Value));
      end if;
   end Set_Value;



   --  ------------------------------
   --  Get the bean attribute identified by the name.
   --  ------------------------------
   overriding
   function Get_Value (From : in Stat_Bean;
                       Name : in String) return Util.Beans.Objects.Object is
   begin
      if Name = "kind" then
         return Ticket_Type_Objects.To_Object (From.Kind);
      elsif Name = "priority" then
         return Util.Beans.Objects.To_Object (Long_Long_Integer (From.Priority));
      elsif Name = "count" then
         return Util.Beans.Objects.To_Object (Long_Long_Integer (From.Count));
      elsif Name = "time" then
         return Util.Beans.Objects.To_Object (Long_Long_Integer (From.Time));
      elsif Name = "remain" then
         return Util.Beans.Objects.To_Object (Long_Long_Integer (From.Remain));
      elsif Name = "done" then
         return Util.Beans.Objects.To_Object (Long_Long_Integer (From.Done));
      end if;
      return Util.Beans.Objects.Null_Object;
   end Get_Value;


   --  ------------------------------
   --  Set the value identified by the name
   --  ------------------------------
   overriding
   procedure Set_Value (Item  : in out Stat_Bean;
                        Name  : in String;
                        Value : in Util.Beans.Objects.Object) is
   begin
      if Name = "kind" then
         Item.Kind := Ticket_Type_Objects.To_Value (Value);
      elsif Name = "priority" then
         Item.Priority := Util.Beans.Objects.To_Integer (Value);
      elsif Name = "count" then
         Item.Count := Util.Beans.Objects.To_Integer (Value);
      elsif Name = "time" then
         Item.Time := Util.Beans.Objects.To_Integer (Value);
      elsif Name = "remain" then
         Item.Remain := Util.Beans.Objects.To_Integer (Value);
      elsif Name = "done" then
         Item.Done := Util.Beans.Objects.To_Integer (Value);
      end if;
   end Set_Value;

   procedure Op_Load (Bean    : in out Report_Bean;
                      Outcome : in out Ada.Strings.Unbounded.Unbounded_String);
   procedure Op_Load (Bean    : in out Report_Bean;
                      Outcome : in out Ada.Strings.Unbounded.Unbounded_String) is
   begin
      Report_Bean'Class (Bean).Load (Outcome);
   end Op_Load;
   package Binding_Report_Bean_1 is
     new ASF.Events.Faces.Actions.Action_Method.Bind (Bean   => Report_Bean,
                                                      Method => Op_Load,
                                                      Name   => "load");

   Binding_Report_Bean_Array : aliased constant Util.Beans.Methods.Method_Binding_Array
     := (1 => Binding_Report_Bean_1.Proxy'Access
     );

   --  ------------------------------
   --  This bean provides some methods that can be used in a Method_Expression.
   --  ------------------------------
   overriding
   function Get_Method_Bindings (From : in Report_Bean)
                                 return Util.Beans.Methods.Method_Binding_Array_Access is
      pragma Unreferenced (From);
   begin
      return Binding_Report_Bean_Array'Access;
   end Get_Method_Bindings;
   --  ------------------------------
   --  Get the bean attribute identified by the name.
   --  ------------------------------
   overriding
   function Get_Value (From : in Report_Bean;
                       Name : in String) return Util.Beans.Objects.Object is
   begin
      return Util.Beans.Objects.Null_Object;
   end Get_Value;


   --  ------------------------------
   --  Set the value identified by the name
   --  ------------------------------
   overriding
   procedure Set_Value (Item  : in out Report_Bean;
                        Name  : in String;
                        Value : in Util.Beans.Objects.Object) is
   begin
      null;
   end Set_Value;


end Jason.Tickets.Models;
